import os
import re
import asyncio
import spotipy
from shazamio import Shazam
from pydub import AudioSegment
from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth
from dotenv import load_dotenv

async def analyze_mix(video_file):
    INTERVAL_MINUTES = 3
    SAMPLE_DURATION = 10

    shazam = Shazam()

    print(f"Loading {video_file}...")
    full_audio = AudioSegment.from_file(video_file)

    total_length_ms = len(full_audio)
    interval_ms = INTERVAL_MINUTES * 60 * 1000
    sample_ms = SAMPLE_DURATION * 1000

    detected_songs = []

    print("Starting detection loop...")

    for position in range(0, total_length_ms, interval_ms):
        audio_slice = full_audio[position : position + sample_ms]

        temp_filename = "temp_slice.mp3"
        audio_slice.export(temp_filename, format="mp3")

        try:
            current_minute = position // 1000 // 60
            print(f"Analyzing minute {current_minute}...")

            out = await shazam.recognize(temp_filename)

            if 'track' in out:
                song_title = out['track']['title']
                artist_name = out['track']['subtitle']

                if not detected_songs or detected_songs[-1] != (song_title, artist_name):
                    print(f"[{current_minute}m] Found: {song_title} - {artist_name}")
                    detected_songs.append((song_title, artist_name))
            else:
                print(f"[{current_minute}m] No result.")

        except Exception as e:
            print(f"Error at minute {current_minute}: {e}")
    
    print("\n--- Final Setlist ---")
    for song in detected_songs:
        print(song)

    if os.path.exists("temp_slice.mp3"):
        os.remove("temp_slice.mp3")

    return detected_songs

songs = []
found_uris = []

load_dotenv()

CLIENT_ID = os.getenv("SPOTIPY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIPY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIPY_REDIRECT_URI")
SHAZAM_KEY = os.getenv("SHAZAM_API_KEY")

def create_playlist(playlist_name, found_uris):
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope="playlist-modify-public"
        ))
    
    user_id = sp.current_user()['id']
    print(f"Authenticated as: {user_id}")

    print(f"Creating playlist: {playlist_name}...")
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=True,
        description="Generated by Python script from DJ Mix"
    )
    playlist_id = playlist['id']
    print(f"Playlist created! ID: {playlist_id}")

    if found_uris:
        for i in range(0, len(found_uris), 100):
            chunk = found_uris[i : i + 100]
            sp.playlist_add_items(playlist_id, chunk)
            print(f"Added {len(chunk)} tracks...")

        print(f"Success! View your playlist here: {playlist['external_urls']['spotify']}")
    else:
        print("No tracks found to add")

def clean_song_title(song_name):
    song_name = re.sub(r"\(.*?\)", "", song_name)
    song_name = re.sub(r"\[.*?\]", "", song_name)

    keywords = [
        "Extended Mix", "Original Mix", "Club Mix", "Radio Edit", 
        "feat\.", "ft\.", "Remix"
    ]

    for word in keywords:
        song_name = re.sub(f"(?i){word}", "", song_name)
        
    return song_name.strip()


def get_song_uri(song_name, artist_name=None):
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
        client_id = CLIENT_ID,
        client_secret = CLIENT_SECRET
    ))

    if artist_name:
        query = f"track:{song_name} artist:{artist_name}"
    else:
        query = f"track:{song_name}"

    try:
        result = sp.search(q=query, type='track', limit=1)

        tracks = result['tracks']['items']
        if tracks:
            uri = tracks[0]['uri']
            print(f"Found: {tracks[0]['name']} by {tracks[0]['artists'][0]['name']}")
            return uri
    except:
        pass

    cleaned_song = clean_song_title(song_name)

    if cleaned_song == song_name:
        print("   -> No match found.")
        return None
    
    query_clean = f"track:{cleaned_song} artist:{artist_name}"
    print(f"Attempt 2:  {query_clean}")

    try:
        result = sp.search(q=query_clean, type='track', limit=1)
        tracks = result['tracks']['items']
        if tracks:
            uri = tracks[0]['uri']
            print(f"Found: {tracks[0]['name']} by {tracks[0]['artists'][0]['name']}")
            return uri
        else:
            print(f"No match found for: {song_name}")
            return None
    except Exception as e:
        print(f"Error searching for {song_name}: {e}")
        return None
    
PLAYLIST_NAME = "Test"
VIDEO_FILE = "YTDown.com_YouTube_Classic-House-Grooves-&-Good-Vibes-Chill_Media_5pu5ZGFWZ98_006_144p.mp4"

async def main():
    print("--- STEP 1: SHAZAM IDENTIFICATION ---")
    identified_songs = await analyze_mix(VIDEO_FILE)
    
    if not identified_songs:
        print("No songs found. Exiting.")
        return

    print("\n--- STEP 2: SPOTIFY AUTHENTICATION ---")
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        scope="playlist-modify-public",
        open_browser=True
    ))
    user_id = sp.current_user()['id']
    print(f"Logged in as: {user_id}")

    print("\n--- STEP 3: SEARCHING SPOTIFY ---")
    track_uris = []
    for song, artist in identified_songs:
        uri = get_song_uri(song, artist)
        if uri:
            track_uris.append(uri)

    if track_uris:
        print(f"\n--- STEP 4: CREATING PLAYLIST '{PLAYLIST_NAME}' ---")
        playlist = sp.user_playlist_create(
            user=user_id, 
            name=PLAYLIST_NAME, 
            description="Auto-generated by Shazamio & Spotipy"
        )
        
        sp.playlist_add_items(playlist['id'], track_uris)
        
        print(f"DONE! Playlist created: {playlist['external_urls']['spotify']}")
    else:
        print("Could not find any matching tracks on Spotify.")

if __name__ == "__main__":
    asyncio.run(main())

'''
with open("song_list2.txt") as song_list:
    for song in song_list:
        songs.append(song)


for line in songs:
    if " - " in line:
        parts = line.split(" - ")
        song = parts[1]
        artist = parts[0]
        uri = get_song_uri(song, artist)
    else:
        uri = get_song_uri(line)

    if uri:
        found_uris.append(uri)

print(f"\nCollected {len(found_uris)} URIs ready for playlist creation.")

create_playlist("Test", found_uris)
'''